### ISSUE TITLE
Checking if multiselect field contains specific value

### ISSUE THREAD

**Issue by joh-sch** [rasteiner/k3-whenquery#23]
I'm trying to use the whenquery plugin to show/hide fields depending on whether a multiselect field is holding a certain value. 

In the example below I'm trying to only display the `svg` field if the SVG option is selected in the `features` field, using the `::any` operator. This does not work.

```yml
features:
  type: multiselect
  options:
    text: Text
    svg: SVG
    img: Image
  width: 1/4

svg:
  type: files
  max: 1
  accept: image/svg+xml
  layout: cardlets
  whenQuery: features.split()::any["SVG", "svg"]
```

I've also tried using the `=~` search operator, which also does not seem to work.

```yml
svg:
  type: files
  max: 1
  accept: image/svg+xml
  layout: cardlets
  whenQuery: features.split() =~ ["SVG", "svg"]
```

Can this be done and, if so, how?
