### ISSUE TITLE
required field handling

### ISSUE THREAD

**Issue by teichsta** [rasteiner/k3-whenquery#9]
Hi,

thanks for providing this great plugin! I am wondering if there is a way to deal with required fields like in kirby itself. If a required field is hidden a page is considered "valid". While whenQuery doesn't seem to take this into account. Even hidden fields are evaluated while changing the pages state, correct?

Is there a way around it?

Best, Thomas E.-E.

**Comment by rasteiner** [comment]
In theory this plugin should behave exactly like the `when` property of standard Kirby, since it overrides the function that `when` uses (the [`meetsCondition` function](https://github.com/getkirby/kirby/blob/0a1f15d39a4be3e5ab6fae868d2ff607fab3dce9/panel/src/components/Forms/Fieldset.vue#L113-L130)). It doesn't actually actively "hide" sections and fields, it just answers the question whether a field should be hidden or not. That's why I find it really strange that it behaves differently from the normal `when`. 

Could you provide an example blueprint?

**Comment by quentin-f451** [comment]
Hi, 
I do have the same problem with required fields when they are hidden. Here is a simplified example:

```yml
category:
  type: checkboxes
  options:
    value1: Value 1
    value2: Value 2
firstTitle:
  type: text
  required: true
  whenQuery: category ::any($ = "value1")
secondTitle:
  type: text
  required: true
  whenQuery: category ::any($ = "value2")
```

If I only select `value1` in the category fields, I still have an alert if `secondTitle` (that is hidden) is empty.
